define Unknown = Character('???', color="#ffe763")
define Chaos = Character('???', color="#ffe763")
define ChaosP = Character('Хаос', color="#ffe763")
define Hero = Character('Я', color="0000b3")
define Lisa = Character('Лиза', color="#82057b")
define Alice = Character('Алиса', color="#ffd863")
define Eva = Character('Ева', color="#ff6b89")
define Worker = Character('Работница цветочного', color="#ff6b89")
define Ludmila = Character('Людмила Владимировна', color="#7ad40e")
